# Generated by Django 2.2.1 on 2019-05-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_information',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
