# Generated by Django 2.2.1 on 2019-05-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190526_2126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileApi',
        ),
    ]
