# Generated by Django 2.2.1 on 2019-05-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowawards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_comments',
        ),
    ]
