# Generated by Django 2.2.1 on 2019-05-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowawards', '0002_remove_image_image_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_caption',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='photo_image',
            new_name='project_image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='project_title',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
